import { ApiProperty } from "@nestjs/swagger"
import { Prop } from "@root/_shared/utils/decorators"
import { Expose } from "class-transformer"

export class VerifySignaturePayload {
	@ApiProperty({
		description: "Original message that was signed",
		example: "MQTiGPGVJzWI"
	})
	@Prop()
	message: string

	@ApiProperty({
		description:
			"Signature generated by signing the message with the wallet in base64",
		example:
			"yMnhiX6xvQTneQB/0phtxtj4m/Js584xVPAx9k1v0r7jS8RSw59iuKj3vXKk37ZmqtdQZbKY9Sf1Npi+oWefDw=="
	})
	@Prop()
	signature: string

	@ApiProperty({
		description: "Public key of the wallet that generated the signature",
		example: "ES69bn51QABsJ5G5Kp2LZW524MCSdxhP1a7dHB84nQ12"
	})
	@Prop()
	publicKey: string
}

export class VerifySignatureResponse {
	@ApiProperty({
		description: "JWT token for authenticated requests",
		example: "eyJhbGciOiJIUzI1NiIs..."
	})
	@Expose()
	token: string
}
