export const SETTING_KEYS = {
	KING_OF_HILL_MARKET_CAP: "KING_OF_HILL_MARKET_CAP",
	LATEST_SIGNATURE_SCANNED_PONZ: "LATEST_SIGNATURE_SCANNED_PONZ",
	LATEST_SIGNATURE_SCANNED_RAYDIUM: "LATEST_SIGNATURE_SCANNED_RAYDIUM"
}
